# Site settings
title: Richard Annand's CV
description: Richard Annand's CV
favicon: /assets/img/avatar.JPG
# baseurl: /
# url: https://ddbullfrog.github.io/resumecard
rss_url: /pages/atom.xml
google_analytics: UA-155118582-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Richard Annand
  title: Systems Engineer & Developer
  address: Edinburgh, United Kingdom
  email: richard@systemsmystery.cloud
  link: https://blog.ohheyrj.co.uk
  github: rj175
  linkedin: richardannand
  twitter: rj175
  gavatar: /resumecard/assets/img/avatar.JPG
  stackoverflow:
  workHistory:
    - work1:
      company: Registers of Scotland
      location: Edinburgh, United Kingdom
      title: AWS Engineer
      started: 2019
      duration: ( August 2019 - Present)
      description: Manage and configure AWS environment for production use.
    - work2:
      company: Registers of Scotland
      location: Edinburgh, United Kingdom
      title: Senior Platform Engineer
      started: 2018
      duration: (October 2018 -  December 2019)
      description: Manage, monitor and configure VMware estate including VMWare vCenter, VMware Site Recovery Manager, NetApp, EMC VNX, EMC RecoverPoint. Managed in-house private cloud (VXBlock).
  educationHistory:
    - education1:
      organization: Jewel & Esk College
      location: Edinburgh, United Kingdom
      degree: HND
      major: Technical Support
      started: 2008
      duration: (2008 - 2009)
    - education2:
      organization: Jewel & Esk Vally College
      location: Dalkeith, Midlothian
      degree: HNC
      major: Computing
      started: 2007
      duration: (2007 - 2008)
  languages:
    - language1:
      name: English
      proficiency: Native
  programmingSkills:
    - skill1:
      name: VMware
      percentage: 100%
    - skill2:
      name: AWS
      percentage: 25%
    - skill3:
      name: Python
      percentage: 50%
    - skill4:
      name: PowerShell
      percentage: 70%
    - skill5:
      name: Typescript
      percentage: 10%
