version: 0.2

phases:
  install:
    commands:
      - bundle install
  pre_build:
    commands:
      - jekyll clean
  build:
    commands:
    - jekyll build
artifacts:
  files:
    - './**/*'
  base-directory: _site
  name: cv-ohheyrj-co-uk-$(date +%Y-%m-%d).zip

